# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    derived_data_path = "/tmp/BsuirDerivedData/"
    scheme = "AppStoreSnapshotsUITests"

    devices = [
      "iPhone 8 Plus", # 5.5" Display
      "iPhone 11 Pro Max", # 6.5" Display
      "iPhone 15 Pro Max", # 6.7" Display
      "iPhone 15 Pro",
      "iPad Pro (12.9-inch) (6th generation)",
    ]

    run_tests(
      build_for_testing: true,
      code_coverage: false,
      output_files: "./test_output",
      derived_data_path: derived_data_path,
      devices: devices,
      scheme: scheme
    )

    capture_screenshots(
      devices: devices,
      derived_data_path: derived_data_path,
      languages: [
        "en-US",
        "ru-RU",
        "uk-UA",
      ],
      scheme: scheme,
      test_without_building: true
    )
  end

  desc "Upload screenshots to app store"
  lane :upload_screenshots do
    api_key = app_store_connect_api_key(
      key_id: "F663NPYK73",
      issuer_id: "69a6de7c-f7df-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_F663NPYK73.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_app_store(
      screenshots_path: "./static/snapshots_to_upload",
      overwrite_screenshots: true
    )
  end
end
