# Where should the resulting screenshots be stored?
output_directory("./static/snapshots")

# clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)