#!/bin/bash

cat > $1 << EOL
// DO NOT EDIT!
// This file is auto-generated by build phase
import Foundation

public struct EnvVariables: Equatable {
    /// \`TELEMETRY_DECK_APP_ID\`
    public let telemetryDeckAppId = "${TELEMETRY_DECK_APP_ID}"

    public static let generated = EnvVariables()
}
EOL